### PR TITLE
Fix scrollbar selector

### LINKED ISSUE #49: Scrollbar shows an error if the selector does not exist
**Describe the bug**
When I use the scrollbar module if the selector does not exist on the page an error appears where it cannot be found.

**To Reproduce**
1. Import ScrollBar.
2. Load a page without selector.

**Expected behavior**
That the error does not appear.

### PR DESCRIPTION
**Pull request by javipuche**
fix: Now the scrollbar exposes the instance correctly

Close #49

### CODE REVIEW

File: src/modules/ScrollBar/index.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+        this.options = options
+        this.init()
+    }
+
+    init () {
+        this.createScrollBar()
+    }
+
+    createScrollBar () {
+        if (this.selector && this.selector.length !== undefined) {
```
Comment (JorgeRaboso) [inline src/modules/ScrollBar/index.js]: unnecesary comprobation, make a querySelectorAll to comprove if exists

File: src/modules/ScrollBar/index.js [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+            this.selector.forEach(el => this.getPluginInstance(el))
+        } else if (this.selector) {
+            this.getPluginInstance()
```
Comment (jjlmoya) [inline src/modules/ScrollBar/index.js]:
```javascript
this.instance =  this.getPluginInstance();
```

File: src/modules/ScrollBar/index.js [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+        this.selector = selector
+        this.options = options
+        this.init()
+    }
+
+    init () {
+        this.createScrollBar()
+    }
+
+    createScrollBar () {
```
Comment (jjlmoya) [inline src/modules/ScrollBar/index.js]: This loop should be managed by a manager instead of a clase, 1 instance per class
